Read the Table_Character correctly to read to the end of the record b…
NASA-PDS/validate pull request #338
Opened 2021-05-05 16:00 UTC by qchaupds

…ased on record length instead of the normal <CR><LF> and null pointer should not show up.

Closes NASA-PDS/validate#325, NASA-PDS/validate#335

This pull request resolves two issues: Read the Table_Character correctly and corrected the null pointer when checking for a command line parameter.

Tested in DEV for #325
Previously would result in ERROR because it was reading the file line by line, which causes the record to end prematurely

% validate -R pds4.label --skip-context-validation -r report_github325_label_valid.json -s json -t src/test/resources/github325/crs009x.xml

Tested in DEV for #335
Three different ways to process a target, none should throw an exception.

% validate -R pds4.label  --skip-context-validation -r report_github335_as_label.json   -s json -t src/test/resources/github335/minimal_test_product.xml 
% validate   --skip-context-validation -r report_github335_as_target.json   -s json -t src/test/resources/github335/*.xml 
% validate   --skip-context-validation -r report_github335_as_dir.json   -s json -t src/test/resources/github335

2021-05-05 17:39 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java
> +      // Given a text table object, determine if it a line oriented table or not.  A line-oriented table contains some record delimiter and optional record_length.
@qchaupds can we add this as a javadoc?

```java
/**
 * Given a text table object, determine if it a line oriented table or not.  A l ...
 **/
```

2021-05-05 17:39 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java
> +      // Take a peek and read the first line from the file and retrieve the line length.
@qchaupds can we add this as a javadoc?

```java
/**
 * Given a text table object, determine if it a line oriented table or not.  A l ...
 **/
```

2021-05-05 17:39 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java
> +          // read past the defined number of records.
@qchaupds if there is data beyond the number of records defined, this can be considered a "footer" for the data and we should not assume anything about this data and/or manually read the data.

we should just throw a warning that there is more data than expected based upon the number of rows (I thought we already did this?).

this could be used for calculating the file size, but we should not do any more validation with the assumption these are actual rows of the table

2021-05-05 17:39 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java
> +          // read past the defined number of records.
looking at the code below, i may be misunderstanding what is happening here, but we shouldn't be checking any of the data in the "footer" of the data. we should just throw a warning and use the extra info to calculate the file size

2021-05-05 18:06 UTC, qchaupds commented on src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java
> +      // Given a text table object, determine if it a line oriented table or not.  A line-oriented table contains some record delimiter and optional record_length.
Done now and pushed to github.

2021-05-05 18:06 UTC, qchaupds commented on src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java
> +      // Take a peek and read the first line from the file and retrieve the line length.
Done now and pushed to github.

2021-05-05 18:07 UTC, qchaupds commented on src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java
> +          // read past the defined number of records.
The code you are asking about is extracted AS-IS from a very large function.   Perhaps we can look at this in a separate ticket.

2021-05-07 16:57 UTC, jordanpadams requested changes
@qchaupds looks like we are missing the test data

2021-05-07 17:31 UTC, qchaupds commented
My bad @jordanpadams .  Both resources are just checked in:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 116 % git commit -m "Add missing test resources"
[#325_335 997f9ff] Add missing test resources
 Committer: Qui T Chau <qchau@pds-dev3.jpl.nasa.gov>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 5 files changed, 476 insertions(+)
 create mode 100644 src/test/resources/github325/crs009x.tab
 create mode 100644 src/test/resources/github325/crs009x.xml
 create mode 100644 src/test/resources/github335/minimal_test_product.csv
 create mode 100644 src/test/resources/github335/minimal_test_product.tab
 create mode 100644 src/test/resources/github335/minimal_test_product.xml
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 117 % git push
Counting objects: 16, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 4.29 KiB | 0 bytes/s, done.
Total 12 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To git@github.com:NASA-PDS/validate.git
   89e36ca..997f9ff  #325_335 -> #325_335

2021-05-07 21:37 UTC, jordanpadams commented
per last commit, also resolves #336

2021-05-07 23:10 UTC, merged