Check Header of File_Area_Ancillary and provide meaningful error mess…
NASA-PDS/validate pull request #393
Opened 2021-08-26 16:36 UTC by qchaupds

…ages when the offset overlap between Header and table data or table fields overlap between each others.

1. Add test resources :src/test/resources/github361
2. Add meaningful error message when fields overlap :src/main/java/gov/nasa/pds/tools/validate/content/table/FieldValueValidator.java
3. Add logic to check for overlap of header total length with table offset, and add meaningful error message when offset is incorrect :src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java
4. Modify logic to read Table_Character tags from all possible main tags not just Product_Observational :src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableFieldDefinitionRule.java

Refs:

https://github.com/nasa-pds/validate/issues/361 validate does not check Header of a File_Area_Ancillary nor does not provide a meaningful error message for an incorrect Table_Character offset

Closes https://github.com/nasa-pds/validate/issues/361 validate does not check Header of a File_Area_Ancillary nor does not provide a meaningful error message for an incorrect Table_Character offset

The error messages weren't as meaningful to the user so extra verbiage were added so the user can make the correction in the label.
Also, previously, the code was not reading the Table_Character tag but it does now.
The reason was the Table_Character can also be File_Area_Ancillary product.

Since issue #361 is a follow on issue #257, a new test set was added to allow the tester to validate the meaningful-ness of the error messages.
No new regression tests were added.

Tested in DEV:

Case 1:  The offsets and headers are good.

```
% validate -R pds4.label --skip-context-reference-check -r report_github361_label_valid_mini_good_offset.json  -s json -t src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.good.xml
```
Case 2: The table offset is too early before the header total length ends.
```
% validate -R pds4.label --skip-context-reference-check -r report_github361_label_invalid_mini_offset_too_early.json  -s json -t src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.too.early.xml >& t11
```
Case 3: The table offset is past the header total length (which is OK) but throws off table validation since the fields are all wrong because
the first field is starting in the middle of the 1st record and not the first byte.
```
% validate -R pds4.label --skip-context-reference-check -r report_github361_label_invalid_mini_offset_late_is_ok_but_throws_of_table_validation.json  -s json -t src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.late.is.ok.but.throws.off.table.validation.xml
```
Case 4 :  The start position of field 2 is too early and overlaps with field 1
```
% validate -R pds4.label --skip-context-reference-check -r report_github361_label_invalid_mini_header.json  -s json -t src/test/resources/github361/maven_orb_rec_210101_210401_v1.invalid.minimal.header.xml
```

2021-08-26 17:59 UTC, jordanpadams requested changes
@qchaupds a couple related issues here:

- [ ] 1. offset does not appear to be read or used in content validation

when I change the offset of your product that fails to 500, the product validates successfully. however, that should put the reader somewhere in the middle of the data file, which should throw an error. it seems like validate may just be using the header offset + object_length to start reading, when it should simply always be using the offset for where to start in the file.

- [ ] 2. the header / offset overlap check must apply to all Table_*
when I change your test product to use Table_Binary instead of Table_Character, it does not properly throw the error message you are referring to.

2021-08-26 19:04 UTC, qchaupds commented
@jordanpadams Issue 1: I am not able to see the same issue you see.  Can you be more specific on the label you are using?

Added a new label: src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.late.is.ok.but.throws.off.table.validation.500.xml
where the offset is changed from 300 to 500 and the error can be observed (because it threw everything off):

This test fail because the offset is in the middle of the table.

```
% validate -R pds4.label --skip-context-reference-check -r report_github361_label_invalid_mini_offset_late_is_ok_but_throws_of_table_validation_500.json  -s json -t src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.late.is.ok.but.throws.off.table.validation.500.xml >& t12

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 110 % egrep "status|label" report_github361_label_invalid_mini_offset_late_is_ok_but_throws_of_table_validation_500.json
    "ruleType": "pds4.label",
      "status": "FAIL",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.late.is.ok.but.throws.off.table.validation.500.xml",
```

This also fail because it is in the middle of the table (with the offset of 300)

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 112 % validate -R pds4.label --skip-context-reference-check -r report_github361_label_invalid_mini_offset_late_is_ok_but_throws_of_table_validation.json  -s json -t src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.late.is.ok.but.throws.off.table.validation.xml >& t12

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 113 %  egrep "status|label" report_github361_label_invalid_mini_offset_late_is_ok_but_throws_of_table_validation.json
    "ruleType": "pds4.label",
      "status": "FAIL",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.late.is.ok.but.throws.off.table.validation.xml",
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 114 % 
```

Can you clarify if the offset is late (beyond the header) is an error because it is beyond the header (You had mentioned that it was OK in the past because the user wanted to skip more after the header) or because the parsing is off because the fields don't align anymore with their expected formats?  Currently, the code is depending on the parsing to fail to report the error.

2021-08-26 19:27 UTC, qchaupds commented
@jordanpadams My bad.  I just realized a file is missing in github.  Stay tuned.  Don't know what happened.

2021-08-26 19:48 UTC, qchaupds commented
@jordanpadams Please grab latest commit 7ebff46 and have another review.

The following shows validate for the label with "Table_Binary":
```
validate -R pds4.label --skip-context-reference-check -r report_github361_label_invalid_mini_offset_late_is_ok_but_throws_of_table_validation_table_binary.json -s json -t src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.late.is.ok.but.throws.off.table.validation.table.binary.xml > & t12

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 110 % egrep "status|label"  report_github361_label_invalid_mini_offset_late_is_ok_but_throws_of_table_validation_table_binary.json            
    "ruleType": "pds4.label",
      "status": "FAIL",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github361/maven_orb_rec_210101_210401_v1.minimal.offset.late.is.ok.but.throws.off.table.validation.table.binary.xml",
```
Both issues should be resolved now.

2021-08-27 01:30 UTC, jordanpadams approved these changes
@qchaupds looks good! very weird when I set the offset in `maven_orb_rec_210101_210401_v1.minimal.offset.too.early.xml` to be basically 268-270, it still validates successfully. but i guess that is just a coincidence that those 3 bytes don't throw off the validation of the rows/fields.

2021-08-27 01:30 UTC, merged