Fix bug for label with FITS file with multiple Header tags before and…
NASA-PDS/validate pull request #420
Opened 2021-10-19 16:12 UTC by qchaupds

… after Table_Binary tag

1. Add test resources : src/test/resources/github416
2. New class to remove comments from XML file  : src/main/java/gov/nasa/pds/tools/util/DocumentUtil.java
3. New class to count number of header tags from file before Table_ tags : src/main/java/gov/nasa/pds/tools/util/TableUtil.java
4. Fix bug logic when summing up header size by being aware of how many headers before the Table_ tag : src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java
5. Add new type FIELDS_MISMATCH to count errors in regression test  : src/test/java/cucumber/StepDefs.java
6. Add 4 new regression tests : src/test/resources/features/validate.feature

Refs:

https://github.com/nasa-pds/validate/issues/416 validate 2.1.0 indicates the table offset is not correct when validating a binary table inside a FITS

Closes https://github.com/nasa-pds/validate/issues/416 validate 2.1.0 indicates the table offset is not correct when validating a binary table inside a FITS

A bug occured due the label has many "Header" tags but only two were meant for the "Table_Binary".  The third "Header" was meant for the "Array_3D_Image".
The fix was to count the number of "Header" tagbs before the "Table_" field.  With this fix, the header size is now calculated correctly.

Tested in DEV:

Since user provided two labels that were valid but validate module marked them as invalid, there are 4 tests to cover 2 valid cases and 2 invalidate cases.

Case 1:

Running validate against first valid label.  No error expected.
```
% validate -R pds4.label -r report_github416_label_valid_1.json  -s json -t src/test/resources/github416/mix_raw_calib_mixs-c_sw_offset_table_20160301.xml
```

Case 2:
Running validate against first label with the offset still inside the header.  Expect one error for error.table.fields_mismatch type.

```
% validate -R pds4.label -r report_github416_label_invalid_1.json  -s json -t src/test/resources/github416/mix_raw_calib_mixs-c_sw_offset_table_20160301_invalid.xml
```

Case 3:
Running validate against a second valid label.  No error expected.

```
% validate -R pds4.label -r report_github416_label_valid_2.json  -s json -t src/test/resources/github416/phe_misc_temperature_reference_20190524.xml
```

Case 4:
Running validate against a second label with the offset still inside the header.  Expect one error for error.table.fields_mismatch type.

```
% validate -R pds4.label -r report_github416_label_invalid_2.json  -s json -t src/test/resources/github416/phe_misc_temperature_reference_20190524_invalid.xml
```

2021-10-21 21:41 UTC, jordanpadams requested changes

2021-10-21 21:41 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/util/TableUtil.java
> +      String cleanDocument = this.documentUtil.getDocumentWithoutComments(fileUrl);
@qchaupds what is the rationale for removing comments from the file? you mention `since the tags we are looking for`, what tags are we looking for exactly?

2021-10-21 21:49 UTC, qchaupds commented on src/main/java/gov/nasa/pds/tools/util/TableUtil.java
> +      String cleanDocument = this.documentUtil.getDocumentWithoutComments(fileUrl);
@jordanpadams The tags we are looking for is "Header" and "Table_Binary", "Table_Delimited", "Table_Character".  The comments should be removed because the tag can be inside a multi-comment.  Does that make sense?

2021-10-21 21:55 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/util/TableUtil.java
> +      String cleanDocument = this.documentUtil.getDocumentWithoutComments(fileUrl);
@qchaupds sorry I'm not quite understanding yet. can you send me an example? or is one of the examples in the test data?

2021-10-21 22:06 UTC, qchaupds commented on src/main/java/gov/nasa/pds/tools/util/TableUtil.java
> +      String cleanDocument = this.documentUtil.getDocumentWithoutComments(fileUrl);
@jordanpadams There are two labels with comments in them in src/test/resources/github416 directory

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 108 % grep -i -A 5 comment src/test/resources/github416/*.xml
src/test/resources/github416/phe_misc_temperature_reference_20190524_invalid.xml:<!-- This is a multi-line comment to be removed by function getDocumentWithoutComments in DocumentUtil.java class
src/test/resources/github416/phe_misc_temperature_reference_20190524_invalid.xml-      <Header> This line should be removed as well.
src/test/resources/github416/phe_misc_temperature_reference_20190524_invalid.xml- -->
src/test/resources/github416/phe_misc_temperature_reference_20190524_invalid.xml-
src/test/resources/github416/phe_misc_temperature_reference_20190524_invalid.xml-      <Header>
src/test/resources/github416/phe_misc_temperature_reference_20190524_invalid.xml-         <name>FITS HEADER</name>
--
src/test/resources/github416/phe_misc_temperature_reference_20190524.xml:<!-- This is a multi-line comment to be removed by function getDocumentWithoutComments in DocumentUtil.java class
src/test/resources/github416/phe_misc_temperature_reference_20190524.xml-      <Header> This line should be removed as well.
src/test/resources/github416/phe_misc_temperature_reference_20190524.xml- -->
src/test/resources/github416/phe_misc_temperature_reference_20190524.xml-
src/test/resources/github416/phe_misc_temperature_reference_20190524.xml-      <Header>
src/test/resources/github416/phe_misc_temperature_reference_20190524.xml-         <name>FITS HEADER</name>
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 109 % 
```

2021-10-22 00:08 UTC, jordanpadams requested changes

2021-10-22 00:08 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/util/DocumentUtil.java
> +      Document doc = Jsoup.parse(documentContent, "", Parser.xmlParser()); // Parse the file as XML.
@qchaupds it looks like we are using an XML Parser to pull out the comments from the document, correct?

at this point, is there are reason we don't just use the XML parser to walk through `File_Area_*` to determine all the necessary offsets?

additionally, `Header` nodes can be intermingled within the `File_Area_*`, they do not have to be at the top of the file. e.g.:
```
<Header>
...
<Table_Character>
...
<Header>
...
<Table_Character>
...
```

For the logic here, I am thinking we need to do a walk through the `File_Area_*` and any time we get an object that contains an offset and a byte size, we check that, and then continue to walk. As a note, this also does not just apply to Table but also to other objects within the PDS (e.g. arrays).

For more details, here are all the different `File_Area_*` possible: https://pds.nasa.gov/datastandards/documents/im/v1/index_1G00.html#class_pds_file_area 

And for `File_Area_Observational` the `has_tagged_object` association could be one of numerous types: https://pds.nasa.gov/datastandards/documents/im/v1/index_1G00.html#class_pds_file_area_observational

2021-10-22 16:14 UTC, qchaupds commented on src/main/java/gov/nasa/pds/tools/util/DocumentUtil.java
> +      Document doc = Jsoup.parse(documentContent, "", Parser.xmlParser()); // Parse the file as XML.
@jordanpadams 

Talking it out for clarification.
```
Referencing this label src/test/resources/github416/ mix_raw_calib_mixs-c_sw_offset_table_20160301.xml

121    <File_Area_Observational>
122       <File>
123          <file_name>mix_raw_calib_mixs-c_sw_offset_table_20160301.fits</file_name>
124          <creation_date_time>2021-10-04T10:55:39Z</creation_date_time>
125          <file_size unit="byte">28800</file_size>
126          <records>2</records>
127          <md5_checksum>f1f1817ef540cd47c63ccad41fd80505</md5_checksum>
128       </File>
129       <Header>
130          <name>FITS HEADER</name>
131          <offset unit="byte">0</offset>
132          <object_length unit="byte">2880</object_length>
133          <parsing_standard_id>FITS 3.0</parsing_standard_id>
134          <description>This product contains MIXS-C software offset tables. These contain offset values for each pixel. These tables are snapshots of the dynamically changing offset table stored in t    he DPU, generated at the time the table was requested.</description>
135       </Header>
136       <Header>
137          <name>FITS EXTENSION HEADER</name>
138          <offset unit="byte">2880</offset>
139          <object_length unit="byte">2880</object_length>
140          <parsing_standard_id>FITS 3.0</parsing_standard_id>
141          <description>FITS extension header for the metadata</description>
142       </Header>
143       <Table_Binary>
144          <name>METADATA</name>
145          <offset unit="byte">5760</offset>
146          <records>2</records>
…
174          </Record_Binary>
175       </Table_Binary>
176       <Header>
177          <name>FITS EXTENSION HEADER</name>
178          <offset unit="byte">8640</offset>
179          <object_length unit="byte">2880</object_length>
180          <parsing_standard_id>FITS 3.0</parsing_standard_id>
181          <description>FITS extension header for the MIXS-C software offset table</description>
182       </Header>
183       <Array_3D_Image>
184          <name>SOFTWARE OFFSET TABLE</name>
185          <local_identifier>SOFTWARE_OFFSET_TABLE</local_identifier>
186          <offset unit="byte">11520</offset>
187          <axes>3</axes>
188          <axis_index_order>Last Index Fastest</axis_index_order>
189          <description>This is a FITS image extension containing the MIXS-C software offset table. This is a 64x64 array of offsets.</description>
190          <Element_Array>
```

The code was blindly counting all the header sizes in the File_Area_Observational object, not realizing it has also counted the Header size at line 176, which is for the Array_3D_Image.

```
795       List<Object> headerObjects = objectAccess.getHeaderObjects(fileArea);
 796       int headerSize = 0;
 797       // How far into the file does the header starts is the headerOffset.
 798       // The headerSize is the number of characters to describe the header of the table.
 799       // headerOffset + headerSize = total header length
 800       int headerOffset = 0;
 801       LOG.debug("validateTableDataContents:headerObjects.size {}",headerObjects.size());
 802       int headerIndex = 0;
 803       for (Object header: headerObjects) {
 804           Header hdr = (Header)header;
 805           headerSize += hdr.getObjectLength().getValue().intValueExact();
 806           headerOffset = hdr.getOffset().getValue().intValueExact(); 
```

The attempt in the fix of TableDataContentValidationRule.java (which it is now validating some kinds of table) was to add a few more lines (809 through 824) to only count the header objects before the Table_Binary tag at line 143.  Help me to understand what the issue is?

```
803       for (Object header: headerObjects) {
 804           Header hdr = (Header)header;
 805           headerSize += hdr.getObjectLength().getValue().intValueExact();
 806           headerOffset = hdr.getOffset().getValue().intValueExact();
 807           // Save the cummulative length of each header but only up to headerSizesArray.length,
 808           // because any values after that is for another object (perhaps an array).
 809           if ((headerSizesArray.length > 0) && (headerIndex < headerSizesArray.length)) {
 810               headerSizesArray[headerIndex] = headerSize;
 811               LOG.debug("validateTableDataContents:headerIndex,headerSizesArray {},{}",headerIndex,headerSizesArray[headerIndex]);
 812           } else {
 813               LOG.debug("validateTableDataContents:headerIndex,headerSize,headerOffset,SKIP {},{},{}",headerIndex,headerSize,headerOffset);
 814           }
 815           LOG.debug("validateTableDataContents:headerObjects.size(),headerSize,hdr.getObjectLength().getValue().intValueExact() {},{},{}",headerObjects.size(),headerSize,hdr.getObjectLength().get     Value().intValueExact());
 816           LOG.debug("validateTableDataContents:headerIndex,headerSize,hdr.getObjectLength().getValue().intValueExact() {},{},{}",headerIndex,headerSize,hdr.getObjectLength().getValue().intValueEx     act());
 817           headerIndex += 1;
 818       }
819       // https://github.com/NASA-PDS/validate/issues/416 Validate 2.1.0 indicates the table offset is not correct when validating a binary table inside a FITS
 820       // This is an important step to fix the bug for issue #416.
 821       // Reset the value of headerSize to the last element in headerSizesArray because this is the true size of the header before the Table object.
 822       if (headerSizesArray.length > 0) {
 823           headerSize = headerSizesArray[headerSizesArray.length-1]; // Reset the value of headerSize to the last element in headerSizesArray
 824       }
 825 


```

2021-10-22 17:10 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/util/DocumentUtil.java
> +      Document doc = Jsoup.parse(documentContent, "", Parser.xmlParser()); // Parse the file as XML.
thanks for the clarification @qchaupds . I think there a few things I am concerned about here, but I will create a new ticket to refactor this class.

2021-10-22 17:11 UTC, merged