Fix bug with MIME type warning on good labels
NASA-PDS/validate pull request #438
Opened 2021-11-02 22:40 UTC by qchaupds

1. Add test resources : src/test/resources/github429
2. Add two missing types 'DOC' and 'DOCX' for 'Microsoft Word' and 'XLS' and 'XLSX' for 'Microsoft Excel' to mime table src/main/resources/validate_default_mime_types.txt
3. Add new regression test : src/test/resources/features/validate.feature

Refs:

https://github.com/nasa-pds/validate/issues/429 validate warns "document standard id ... is not correct" on good labels

Closes https://github.com/nasa-pds/validate/issues/429 validate warns "document standard id ... is not correct" on good labels

Several missing MIME types for "Microsoft Word" were added to validate_default_mime_types.txt to fix the issue: DOC and DOCX
Several missing MIME types for "Microsoft Excel" were added to validate_default_mime_types.txt to fix the issue: XLS and XLSX

Tested in DEV:

Running validate against a valid label with three document types '.DOC', '.TXT' and '.XLS'.  No warning messages are expected.

```
% validate -R pds4.label -r report_github429_label_valid.json   -s json -t  src/test/resources/github429/EPPS_EDR_SIS.xml
 
```

2021-11-03 17:40 UTC, jordanpadams commented
@qchaupds take a look at the description of #429 again. I include some details on design I believe we need here. I think we need to simplify the design a bit.

2021-11-03 20:18 UTC, qchaupds commented
@jordanpadams Please have another look at the PR.

The latest checkin today should now addressed:

1. The check of file extension is now case insensitive.
2. Text file checking should work now.
3. The error message is now changed to include "Expected file suffix(es)".
4. New file extensions have been added to Microsoft Word and Microsoft Excel.

A new bad label has been added to allow to test a bad document product id: src/test/resources/github429/EPPS_EDR_SIS_bad.xml

Running it should have a warning and an improved error message:

validate -R pds4.label -r report_github429_label_invalid.json   -s json -t  src/test/resources/github429/EPPS_EDR_SIS_bad.xml

2021-11-04 03:29 UTC, jordanpadams requested changes
@qchaupds i'm not quite seeing the appropriate warnings. when i run against target EPPS_EDR_SIS.xml , I get these warning messages, and I had a couple questions:

* is this message saying EPPS_EDR_SIS.DOC is not really a Word Doc? the file suffix seems valid?
* `Expected file suffix(es): []` - is this supposed to indicate something?
* Can you take a look at the description for #429? I think there are a few sub-tasks I included there that have note been updated?

> Product Level Validation Results
> 
>   PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github429/EPPS_EDR_SIS.xml
>       WARNING  [warning.file.not_msword_mimetype]   file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github429/EPPS_EDR_SIS.DOC with document standard id 'Microsoft Word' is not correct.  Expected file suffix(es): []
>       WARNING  [warning.file.not_msexcel_mimetype]   file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github429/EPPS_EDR_SIS.XLS with document standard id 'Microsoft Excel' is not correct.  Expected file suffix(es): []
>         1 product validation(s) completed

2021-11-04 15:11 UTC, qchaupds commented
@jordanpadams The label works for me in DEV.  You may have to do a "mvn clean" first because the MIME table (a resource) has been updated.  I think the issues have been addressed.  Please see the messages for the latest commit.  Which ones do you think have not?

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 116 % validate -R pds4.label -r report_github429_label_valid.json   -s json -t  src/test/resources/github429/EPPS_EDR_SIS.xml  >& t6


{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 118 % grep file_name src/test/resources/github429/EPPS_EDR_SIS.xml
                <file_name>e.pdf</file_name>
                <file_name>EPPS_EDR_SIS.DOC</file_name>
                <file_name>EPPS_EDR_SIS.XLS</file_name>
                <file_name>EPPS_EDR_SIS.TXT</file_name>

The report did not show any warning .

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 119 % egrep "status|message"  report_github429_label_valid.json
      "status": "PASS",
      "messages": [],
    "messageTypes": []

```

2021-11-13 20:21 UTC, jordanpadams requested changes
@qchaupds I provided some updates to the code and it now builds and executes correctly for the most part except PDF because the map you are using with the text file overwrites.

please checkout the updates I've made and test out on your own.

I would recommend re-evaluating using a text file, and instead use a JSON file with a dictionary that can be read in and maybe flipped around, e.g.

```
{ 
  standard1: [ extension1, extension2, etc ],
  standard2: [ extension1, extension2, etc ]
}
```

```
  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github429/EPPS_EDR_SIS.xml
      WARNING  [warning.file.not_html_mimetype]   file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github429/EPPS_EDR_SIS_1.foo with document standard 'PDF' is not correct.  Expected file suffix(es): []
        1 product validation(s) completed
```

2021-11-13 20:22 UTC, jordanpadams commented
@qchaupds you can use Gson (already a dependency) to parse the JSON file where you are currently using a scanner and reading by tokens.

2021-11-22 21:37 UTC, qchaupds commented on src/main/java/gov/nasa/pds/tools/util/DocumentUtil.java
> +  private boolean isClassInitialized() {
@sonatype-lift ignore

2021-11-24 19:20 UTC, merged