add unit testing first
NASA-PDS/validate pull request #721
Opened 2023-10-04 16:18 UTC by al-niessner

## 🗒️ Summary
Added check that if delimited table has trailing spaces on number to flag it as data type mismatch error instead of precision.

## ⚙️ Test Data and/or Report
See automated unit tests below (should pass)

## ♻️ Related Issues
Closes #681

2023-10-04 17:39 UTC, jordanpadams requested changes
@al-niessner one thing we can't forget here is in a delimited table, everything within the delimiters is considered part of the "field value", making spaces within any numeric field invalid.

This only applies to delimited tables. You can pad in character tables since they are fixed width fields.

From the Standards Reference:
<img width="643" alt="Screenshot 2023-10-04 at 10 36 55 AM" src="https://github.com/NASA-PDS/validate/assets/33492486/84454264-6ec6-4ff5-a7f8-5e6748209849">

2023-10-04 17:40 UTC, jordanpadams commented
For example if I prepend a space in the field for this CSV, it passes, but it should fail because `\s2.22` is not an `ASCII_Real`

[ff_test.csv](https://github.com/NASA-PDS/validate/files/12806537/ff_test.csv)

2023-10-04 18:36 UTC, nutjob4life approved these changes
LGTM 👍

2023-10-04 18:42 UTC, al-niessner commented
@jordanpadams done

2023-10-05 15:30 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/validate/content/table/FieldValueValidator.java
> +            if (value.trim().length() == value.length()) {
@al-niessner This fixes the whitespace padding when a `field_format` or `validation_format` are specified, but it looks like this may overall be a more inherent bug in handling of whitespace in delimited tables. When I remove the `field_format` attributes from the `ff_del.xml` label, it passes, but it should fail. I created a new requirement here that ties to this handling of whitespace in tables more explicitly: https://github.com/NASA-PDS/validate/issues/722

I would just merge and then work on that requirement, but I think this solution will immediately be changed based upon that requirement

2023-10-05 15:31 UTC, jordanpadams requested changes
See review comment

2023-10-05 16:35 UTC, al-niessner commented on src/main/java/gov/nasa/pds/tools/validate/content/table/FieldValueValidator.java
> +            if (value.trim().length() == value.length()) {
done

2023-10-05 16:57 UTC, al-niessner commented
@jordanpadams 

Oh my. This really breaks a bunch of old tests and specifically #335 that is testing character/delimited tables that are the same. The table in 335 is:

```
2019-08-06T00:00:00Z, This is a test, 1111, 2222, 3333, 4444
2019-08-06T00:01:00Z, This is a test, 1111, 2222, 3333, 4444
2019-08-06T00:02:00Z, This is a test, 1111, 2222, 3333, 4444
2019-08-06T00:03:00Z, This is a test, 1111, 2222, 3333, 4444
````

From XML delimiter is Comma. I do not know if there is a Comma-Space but without it, this file breaks. Does this mean we have been broken all along or that we are going the wrong direction?

2023-10-05 16:58 UTC, jordanpadams commented
@al-niessner hold off on any further implementation on this ticket. we have some comments from people requiring discussion on the standards.

2023-10-05 17:18 UTC, jordanpadams commented
@al-niessner 
> Does this mean we have been broken all along or that we are going the wrong direction?
my brain very well may be taking us in the wrong direction. less pause on this for now. thanks for checking this out.

2023-10-06 19:57 UTC, nutjob4life approved these changes

2023-10-09 21:35 UTC, jordanpadams approved these changes

2023-10-16 16:40 UTC, jordanpadams approved these changes

2023-10-19 20:56 UTC, jordanpadams approved these changes
🎉

2023-10-19 20:56 UTC, jordanpadams commented
CI tests are failing due to intermittent network blocking/outage. But tests run successfully on occasion.

2023-10-19 20:57 UTC, merged