724: remove context ref case reporting
NASA-PDS/validate pull request #759
Opened 2023-11-14 18:59 UTC by al-niessner

# 🗒️ Summary
Remove the case testing

## ⚙️ Test Data and/or Report
No new test data was given. Regression test should pass (automated tests below)

## ♻️ Related Issues
Closes #724

2023-11-14 19:14 UTC, al-niessner commented
Two checks now fail because they look for this mismatch. Cleaned them up and trying again. Historical tickets are #15 and #47.

2023-11-14 20:48 UTC, nutjob4life approved these changes
👍

2023-11-15 01:21 UTC, jordanpadams requested changes

2023-11-15 01:21 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/tools/validate/rule/pds4/ContextProductReferenceValidationRule.java
> -                              ProblemType.CONTEXT_REFERENCE_FOUND_MISMATCH,
@al-niessner This looks like we removed the wrong messages `CONTEXT_REFERENCE_FOUND_MISMATCH`? We still want to check this when we ignore case. I think the problem type we no longer want to catch is `CONTEXT_REFERENCE_FOUND_CASE_MISMATCH`.

2023-11-15 02:48 UTC, jordanpadams commented
Closing this as wontfix. Miscommunication on my part about what should be removed. Linked ticket is duplicate of https://github.com/NASA-PDS/validate/issues/631

2023-11-15 02:48 UTC, closed without merging